spring:
  application:
    name: party-service
  datasource:
    username: ${DB_USERNAME:root}
    url: ${DB_URL:jdbc:mysql://localhost:3306/assign_party}
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASS:root@123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}
server:
  port: 9091
uri:
  leader-service: ${LEADER_SERVICE:http://localhost:9092/leader/}
  development-service: ${DEV_SERVICE:http://localhost:9093/development/}